# Author: Jaydeep Sarkar
# Date: 2026-01-06
# Description: Documentation done targeting OAS 3.x.x, Doc Url is https://swagger.io/specification/ example can be find here https://petstore.swagger.io/?_gl=1*r6pir5*_gcl_au*MTE0NDM4NzQzOS4xNzM2MjMwMTg1

openapi: 3.0.0
info:
  title: Aadhar Housing Finance Limited API
  description: How to talk with AHFL Api
  version: 1.0.0

  contact:
    name: Jaydeep Sarkar
    email: jaydeep.sarkar@intglobal.com

servers:
  - url: http://localhost:8125/api/v1
    description: Local PC development server

components:
  schemas:
    $ref: ./schemas/_index.yaml
  securitySchemes:
    $ref: ./securitySchemes/_index.yaml

tags:
  - name: General
    description: General endpoint to check the health status of the system

paths:
  /health:
    $ref: ./paths/health.yaml

  # Admin user login / password change journey
  /auth/login:
    $ref: ./paths/auth-login.yaml
  /auth/verify-reset-code:
    $ref: ./paths/auth_verify-reset-code.yaml
  /auth/forget-password:
    $ref: ./paths/auth_forget-password.yaml
  /auth/change-password:
    $ref: ./paths/auth_change-password.yaml

  #Admin crm Dashboard
  /admin-crm/crm-requests:
    $ref: ./paths/crm_requests.yaml
  /admin-crm/download-csv:
    $ref: ./paths/admin_Crm_download_Csv.yaml
  /admin-crm/details:
    $ref: ./paths/admin_Crm_details.yaml

  # Admin transaction data
  /admin-transaction/transactions:
    $ref: ./paths/admin_transactions.yaml
  /admin-transaction/download-csv:
    $ref: ./paths/admin_transactions_download_csv.yaml
  /admin-transaction/details:
    $ref: ./paths/admin_transactions_details.yaml

  # Admin Lead endpoints
  /admin-lead/leads:
    $ref: ./paths/admin_lead.yaml
  /admin-lead/leads/download-csv:
    $ref: ./paths/admin_lead_download_csv.yaml
  /admin-lead/details:
    $ref: ./paths/admin_lead_details.yaml

  # Admin customer data
  /admin-customer/customers-list:
    $ref: ./paths/admin_customer.yaml
  /admin-customer/download-csv:
    $ref: ./paths/admin_customer_download_Csv.yaml
  /admin-customer/details:
    $ref: ./paths/admin_customer_details.yaml
